const databaseSystemConceptsAndArch = [
"Database",
"Data Abstraction",
"Data Independence",
"Access Control",
"Data Integrity",
"Data Security",
"Data Persistence",
"Recovery",
"File System",
"DBMS",
"Levels of Data Abstraction",
"Physical Level",
"Logical Level",
"View Level",
"1-Tier Architecture",
"2-Tier Architecture",
"3-Tier Architecture",
"Query Processor",
"Storage Manager",
"Transaction Management",
"Database Administrator",
"DBA",
"Database Design",
"User Access Control",
"User Security",
"Performance Monitoring",
"Performance Optimization",
"Backup and Recovery Management",
]

const EntityRelationshipModel = [
"Conceptual Modeling",
"Dataase Design",
"The Entity-Relationship Model",
"ER",
"Entity Type",
"Entity Sets",
"Strong Entities",
"Weak Entities",
"Attributes",
"Keys",
"Simple Attributes",
"Composite Attributes",
"Single-Valued Attributes",
"Multi-Valued Attributes",
"Derived Attributes",
"Candidate Key",
"Primary Key",
"Foreign Key",
"Relationship Types",
"Relationship Sets",
"One-to-One",
"One-to-Many",
"Many-to-Many",
"Participation Constraints",
"Generalization",
"Specialization",
"Aggregation",
"Generalization",
"Top Down Approach",
"Specialization",
"Bottom Up Approach",
"Aggregation",
"Combining Relationship",
"Extended Entity-Relationship Model",
"EER",
"Superclass",
"Subclass",
"Inheritance",
"Disjoint",
"Overlapping",
]

const RelationalModelAndRelationalAlgebra = [
]